.PHONY: clean All

All:
	@echo "----------Building project:[ max - Debug ]----------"
	@$(MAKE) -f  "max.mk"
clean:
	@echo "----------Cleaning project:[ max - Debug ]----------"
	@$(MAKE) -f  "max.mk" clean
